### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by ghost** [xditya/BotStatus#1]
can you make guide how to deploy at VPS

**Comment by xditya** [comment]
Yes, sure

`git clone https://github.com/xditya/BotStatus`
`cd BotStatus`
`pip3 install -r requirements.txt`
Now make a .env file with all vars as in .env.sample file in the root of the repo, by following these:
`touch .env`
`nano .env`
Enter your details, ctrl+s, ctrl+x, to save and exit nano

Now start the bot using `python3 bot.py`

**Comment by ghost** [comment]
what different message id and chat id?

**Comment by xditya** [comment]
post a message in ur grp/channel and get its id. that message would be edited in future, with the status of you bots.
channel id is the id of your channel/group where the msg is posted

**Comment by ghost** [comment]
Not a valid string
Traceback (most recent call last):
  File "bot.py", line 67, in <module>
    user_bot.loop.run_until_complete(BotzHub())
NameError: name 'user_bot' is not defined

**Comment by xditya** [comment]
recheck your session string

**Comment by ghost** [comment]
https://replit.com/@yuno74/GenerateStringSession-1

I generate with that choose pyrogram

**Comment by xditya** [comment]
This is in telethon; use https://replit.com/@TeamUltroid/UltroidStringSession for a session.

**Comment by ghost** [comment]
telethon.errors.rpcerrorlist.MessageAuthorRequiredError: Message author required (caused by EditMessageRequest)

what I miss?

**Comment by xditya** [comment]
The message must be sent by the account of which the session is generated.

**Comment by ghost** [comment]
JSON CODE:

{
    "update_id": 14730194,
    "message": {
        "message_id": 8700,
        "from": {
            "id": 1311263911,
            "is_bot": false,
            "first_name": "Aɴɪᴍᴇ Rᴇᴘᴜʙʟɪᴄ",
            "username": "Arata74",
            "language_code": "en"

mean 8700 is message id right?

**Comment by ghost** [comment]
> The message must be sent by the account of which the session is generated.

already use

**Comment by xditya** [comment]
Pls use the support group on telegram, @BotzHubChat.
