### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shineii86** [xditya/BotStatus#10]
python3 main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.19/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib
    APP_ID: 
    API_HASH: ***
    BOTS: ***
    SESSION: ***
    CHANNEL_ID: ***
    MESSAGE_ID: ***
[INFO] 2024-04-02 02:40:02,555 - invalid literal for int() with base 10: ''
Error: Process completed with exit code 1.

**Comment by xditya** [comment]
Invalid APP_ID, did you recheck?

**Comment by Shineii86** [comment]
> Invalid APP_ID, did you recheck?

Same error again and again 

Run python3 main.py
  python3 main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.19/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/lib
    APP_ID: ***
    API_HASH: ***
    BOTS: ***
    SESSION: ***
    CHANNEL_ID: ***
    MESSAGE_ID: ***
[INFO] 2024-04-02 04:22:51,901 - invalid literal for int() with base 10: '***'
Error: Process completed with exit code 1.

**Comment by Shineii86** [comment]
Now Working... 🔰
