### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [xditya/BotStatus#3]
https://github.com/yuno74/BotStatus/blob/master/bot.py

help me how to place link preview false. I am noob😢

**Comment by xditya** [comment]
[Line 71](https://github.com/yuno74/BotStatus/blob/cb8eb03dd75f23710e9751129b2cc4784599cc58/bot.py#L71), add `link_preview=False` after `edit_text`.

**Comment by ghost** [comment]
done. how about bot name

![](https://telegra.ph/file/4cbc372df99b61748a24e.jpg)

**Comment by xditya** [comment]
> done. how about bot name
> 
> ![](https://camo.githubusercontent.com/cd29eadbeabbde067313da94165a26806066ce4a9804f3c5fa7cde2a5726a729/68747470733a2f2f74656c656772612e70682f66696c652f3463626333373264663939623631373438613234652e6a7067)

Wdym?

**Comment by ghost** [comment]
for now bot status show username but I want it show name

now
★MissEmiliaBot - ✅

I want
★Emilia - ✅

**Comment by xditya** [comment]
> for now bot status show username but I want it show name
> 
> now
> ★MissEmiliaBot - ✅
> 
> I want
> ★Emilia - ✅

Do it yourself 🙄
That isn't an issue with the repository.
