### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Selfie-bd** [xditya/BotStatus#6]
Bro I fork add var in secret then action > Deploy but not working

**Comment by xdity-is-gay** [comment]
@Selfie-bd @xditya Say With Me @Xditya Is Gay !!! 😏😏😏😏

**Comment by xditya** [comment]
@Selfie-bd provide your logs.

**Comment by Selfie-bd** [comment]
[logs_44.zip](https://github.com/xditya/BotStatus/files/7983517/logs_44.zip)

**Comment by xditya** [comment]
> [logs_44.zip](https://github.com/xditya/BotStatus/files/7983517/logs_44.zip)

use a pastebin.

**Comment by IndrajeethY** [comment]
@Selfie-bd At top right corner there is a cross Mark pls fkin clk and gtfo

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Hurr

**Comment by jainamoswal** [comment]
@Selfie-bd try ↦ [`jainamoswal/BotStatus`](https://github.com/jainamoswal/BotStatus).
